# Trivy Secret Scanning Rules Configuration

# Default secret scanning rules
rules:
  # AWS credentials
  - id: aws-access-key
    category: AWS
    title: AWS Access Key
    severity: CRITICAL
    regex: '(?i)(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'
    keywords:
      - aws_access_key_id
      - aws-access-key-id
      - aws_access_key
      - aws-access-key

  - id: aws-secret-key
    category: AWS
    title: AWS Secret Key
    severity: CRITICAL
    regex: '(?i)[a-z0-9/+=]{40}'
    keywords:
      - aws_secret_access_key
      - aws-secret-access-key
      - aws_secret_key
      - aws-secret-key

  # Database credentials
  - id: postgres-password
    category: Database
    title: PostgreSQL Password
    severity: HIGH
    regex: 'postgres://[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+:[0-9]+/[a-zA-Z0-9._-]+'
    keywords:
      - postgres://
      - postgresql://

  - id: mysql-password
    category: Database
    title: MySQL Password
    severity: HIGH
    regex: 'mysql://[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+:[0-9]+/[a-zA-Z0-9._-]+'
    keywords:
      - mysql://

  # API keys
  - id: openai-api-key
    category: API
    title: OpenAI API Key
    severity: CRITICAL
    regex: 'sk-[a-zA-Z0-9]{48}'
    keywords:
      - openai_api_key
      - openai-api-key
      - OPENAI_API_KEY

  - id: replicate-api-token
    category: API
    title: Replicate API Token
    severity: CRITICAL
    regex: 'r8_[a-zA-Z0-9]{32}'
    keywords:
      - replicate_api_token
      - replicate-api-token
      - REPLICATE_API_TOKEN

  - id: stripe-secret-key
    category: API
    title: Stripe Secret Key
    severity: CRITICAL
    regex: 'sk_(test|live)_[a-zA-Z0-9]{24,}'
    keywords:
      - stripe_secret_key
      - stripe-secret-key
      - STRIPE_SECRET_KEY

  - id: stripe-webhook-secret
    category: API
    title: Stripe Webhook Secret
    severity: HIGH
    regex: 'whsec_[a-zA-Z0-9]{64}'
    keywords:
      - stripe_webhook_secret
      - stripe-webhook-secret
      - STRIPE_WEBHOOK_SECRET

  - id: cloudinary-api-secret
    category: API
    title: Cloudinary API Secret
    severity: HIGH
    regex: '[a-zA-Z0-9_-]{27}'
    keywords:
      - cloudinary_api_secret
      - cloudinary-api-secret
      - CLOUDINARY_API_SECRET

  - id: mixpanel-token
    category: API
    title: Mixpanel Token
    severity: MEDIUM
    regex: '[a-f0-9]{32}'
    keywords:
      - mixpanel_token
      - mixpanel-token
      - MIXPANEL_TOKEN

  # JWT secrets
  - id: jwt-secret
    category: Authentication
    title: JWT Secret
    severity: HIGH
    regex: '[a-zA-Z0-9+/]{32,}={0,2}'
    keywords:
      - jwt_secret
      - jwt-secret
      - JWT_SECRET

  # Generic secrets
  - id: generic-password
    category: Generic
    title: Generic Password
    severity: MEDIUM
    regex: '(?i)(password|passwd|pwd)[\s]*[=:]\s*["\']?[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{}|;:,.<>?]{8,}["\']?'
    keywords:
      - password
      - passwd
      - pwd

  - id: generic-api-key
    category: Generic
    title: Generic API Key
    severity: HIGH
    regex: '(?i)(api[_-]?key|apikey)[\s]*[=:]\s*["\']?[a-zA-Z0-9]{16,}["\']?'
    keywords:
      - api_key
      - api-key
      - apikey

  - id: generic-secret-key
    category: Generic
    title: Generic Secret Key
    severity: HIGH
    regex: '(?i)(secret[_-]?key|secretkey)[\s]*[=:]\s*["\']?[a-zA-Z0-9]{16,}["\']?'
    keywords:
      - secret_key
      - secret-key
      - secretkey

  # Private keys
  - id: rsa-private-key
    category: Encryption
    title: RSA Private Key
    severity: CRITICAL
    regex: '-----BEGIN (RSA )?PRIVATE KEY-----'
    keywords:
      - "-----BEGIN RSA PRIVATE KEY-----"
      - "-----BEGIN PRIVATE KEY-----"

  - id: ssh-private-key
    category: Encryption
    title: SSH Private Key
    severity: CRITICAL
    regex: '-----BEGIN OPENSSH PRIVATE KEY-----'
    keywords:
      - "-----BEGIN OPENSSH PRIVATE KEY-----"

  # Certificate files
  - id: pkcs12-certificate
    category: Encryption
    title: PKCS12 Certificate
    severity: HIGH
    regex: '-----BEGIN CERTIFICATE-----'
    keywords:
      - "-----BEGIN CERTIFICATE-----"

# File path patterns to exclude from secret scanning
allowlist:
  files:
    - "*.md"
    - "*.txt"
    - "*.json.example"
    - "*.env.example"
    - "**/docs/**"
    - "**/examples/**"
    - "**/test/**"
    - "**/tests/**"
  
  paths:
    - "/node_modules/"
    - "/.git/"
    - "/coverage/"
    - "/dist/"
    - "/build/"
    - "/vendor/"

# Custom patterns to ignore (false positives)
ignore:
  patterns:
    - 'example_password'
    - 'your_password_here'
    - 'placeholder_secret'
    - 'dummy_api_key'
    - 'test_secret_key'
    - 'sk-test_123456789'
    - 'AKIA000000000EXAMPLE'