# External Secrets Operator Configuration for AWS Secrets Manager Integration

apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
  labels:
    name: external-secrets-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/external-secrets-operator-role
---
# LinkedIn Headshot Generator Secrets
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: linkedin-headshot-secrets-store
  namespace: linkedin-headshot-production
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        serviceAccount:
          name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkedin-headshot-secrets
  namespace: linkedin-headshot-production
spec:
  secretStoreRef:
    name: linkedin-headshot-secrets-store
    kind: SecretStore
  target:
    name: linkedin-headshot-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: production/linkedin-headshot/database
        property: url
    - secretKey: redis-url
      remoteRef:
        key: production/linkedin-headshot/redis
        property: url
    - secretKey: jwt-secret
      remoteRef:
        key: production/linkedin-headshot/auth
        property: jwt-secret
    - secretKey: replicate-api-token
      remoteRef:
        key: production/linkedin-headshot/ai
        property: replicate-api-token
    - secretKey: cloudinary-cloud-name
      remoteRef:
        key: production/linkedin-headshot/storage
        property: cloudinary-cloud-name
    - secretKey: cloudinary-api-key
      remoteRef:
        key: production/linkedin-headshot/storage
        property: cloudinary-api-key
    - secretKey: cloudinary-api-secret
      remoteRef:
        key: production/linkedin-headshot/storage
        property: cloudinary-api-secret
    - secretKey: stripe-secret-key
      remoteRef:
        key: production/linkedin-headshot/payment
        property: stripe-secret-key
    - secretKey: stripe-webhook-secret
      remoteRef:
        key: production/linkedin-headshot/payment
        property: stripe-webhook-secret
    - secretKey: sentry-dsn
      remoteRef:
        key: production/linkedin-headshot/monitoring
        property: sentry-dsn
---
# Dating Profile Optimizer Secrets
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: dating-optimizer-secrets-store
  namespace: dating-optimizer-production
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        serviceAccount:
          name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dating-optimizer-secrets
  namespace: dating-optimizer-production
spec:
  secretStoreRef:
    name: dating-optimizer-secrets-store
    kind: SecretStore
  target:
    name: dating-optimizer-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: production/dating-optimizer/database
        property: url
    - secretKey: redis-url
      remoteRef:
        key: production/dating-optimizer/redis
        property: url
    - secretKey: jwt-secret
      remoteRef:
        key: production/dating-optimizer/auth
        property: jwt-secret
    - secretKey: openai-api-key
      remoteRef:
        key: production/dating-optimizer/ai
        property: openai-api-key
    - secretKey: cloudinary-url
      remoteRef:
        key: production/dating-optimizer/storage
        property: cloudinary-url
    - secretKey: stripe-secret-key
      remoteRef:
        key: production/dating-optimizer/payment
        property: stripe-secret-key
    - secretKey: stripe-webhook-secret
      remoteRef:
        key: production/dating-optimizer/payment
        property: stripe-webhook-secret
    - secretKey: sentry-dsn
      remoteRef:
        key: production/dating-optimizer/monitoring
        property: sentry-dsn
    - secretKey: segment-write-key
      remoteRef:
        key: production/dating-optimizer/analytics
        property: segment-write-key
---
# Service Account for External Secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: linkedin-headshot-production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/external-secrets-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: dating-optimizer-production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/external-secrets-role
---
# ClusterRole for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-operator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["external-secrets.io"]
  resources: ["secretstores", "externalsecrets", "clustersecretstores"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-operator
subjects:
- kind: ServiceAccount
  name: external-secrets-operator
  namespace: external-secrets-system