apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 30s
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: High
      incrementalQuerying: true
      disableRecordingRules: false
      customQueryParameters: ''
      
  - name: AWS CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: keys
      defaultRegion: us-east-1
      customMetricsNamespaces: 'AWS/ApplicationELB,AWS/EKS,AWS/RDS,AWS/ElastiCache'
    secureJsonData:
      accessKey: ${CLOUDWATCH_ACCESS_KEY}
      secretKey: ${CLOUDWATCH_SECRET_KEY}
      
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: '[logs-]YYYY.MM.DD'
    jsonData:
      interval: Daily
      timeField: '@timestamp'
      esVersion: 8
      includeFrozen: false
      logMessageField: message
      logLevelField: level
      
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686
    jsonData:
      tracesToLogs:
        datasourceUid: elasticsearch
        filterByTraceID: true
        filterBySpanID: true